build: stage-deploy 를 위한 workflows 셋팅
alphaprime-dev/alpha-actions pull request #1
Opened 2022-12-02 05:22 UTC by myeongjunkim

**리뷰어가 작업내용을 이해하기 쉽도록 아래내용을 상세히 작성해주세요.**

## Changes

=> job 단위로 파일화 하여 workfloa_call 적용( called 생성 )
=> 각 파일을 caller 에서 불러와 하나의 job 내에서 step 으로 사용

- build-push.yml
- update-k8s-mainifest.yml
- notify-teams.yml

## Task Link

> **💡** _관련 페이지 링크를 작성해주세요._

[Notion Link](https://www.notion.so/thealphaprime/Resuable-Workflow-c12cd6c8e26549dc9cf80b836e26ea74)

2022-12-06 07:46 UTC, myeongjunkim commented
테스트를 위한 커밋이 대부분이라 file change 내용을 통해 확인 부탁드립니다!

2022-12-07 01:00 UTC, sawaca96 commented on .github/workflows/build-push.yml
> +      - uses: actions/checkout@v3
스텝사이에 여백을 두면 구분이 되서 읽기가 편할 것 같습니다.

2022-12-07 01:02 UTC, sawaca96 commented on .github/workflows/notify-teams.yml
> +name: Reusable Workflow For Deploy
제목 수정 부탁드립니다.

2022-12-07 01:03 UTC, sawaca96 commented on .github/workflows/prod-image-tag.yml
> +        description: "IMAGE_TAG FROM CALLED-JOB"
"IMAGE_TAG FROM CALLED-JOB" -> "IMAGE_TAG FROM RELEAS TAG"로 변경하면 무슨일을 하는지 좀 더 잘 알 수 있을 것 같은데 어떻게 생각하세요?

2022-12-07 01:03 UTC, sawaca96 commented on .github/workflows/prod-image-tag.yml
> +      output1: ${{ steps.step-for-image-tag.outputs.image-tag }}
output1은 syntax인지 궁금합니다. 그게 아니라면 다른 이름을 쓰면 좋을 것 같아요.

2022-12-07 01:04 UTC, sawaca96 commented on .github/workflows/staging-image-tag.yml
> +name: Get Image Tag By SHA Tag
SHA Tag 보다는 Commit SHA가 좀 더 정확한 표현 같습니다.

2022-12-07 01:05 UTC, sawaca96 commented on .github/workflows/update-k8s-mainifest.yml
> +          target_branch: test-ci
target_branch를 변경해야 할 것 같아요

2022-12-07 01:06 UTC, sawaca96 commented on .gitignore
> +staging.yml
이건 어떤 파일을 ignore 하는 걸까요?

2022-12-07 03:50 UTC, myeongjunkim commented on .github/workflows/build-push.yml
> +  called-job:
![image](https://user-images.githubusercontent.com/82504981/206083486-548abfff-dc5b-4828-b94d-c14eee889917.png)

파일명 또한 build-push 로 지정되어 있어서 job name이 반복될 것 같은데 이상 없을까요?
ex) build-push/build-push

2022-12-07 04:20 UTC, myeongjunkim commented on .github/workflows/build-push.yml
> +      - uses: actions/checkout@v3
0dd9bf1 넵 수정하였습니다!

2022-12-07 04:25 UTC, myeongjunkim commented on .github/workflows/prod-image-tag.yml
> +        description: "IMAGE_TAG FROM CALLED-JOB"
c61ce0b 좋은 것 같습니다. 수정하였습니다!

2022-12-07 04:26 UTC, myeongjunkim commented on .github/workflows/staging-image-tag.yml
> +name: Get Image Tag By SHA Tag
c61ce0b 수정하였습니다. 감사합니다!

2022-12-07 04:36 UTC, myeongjunkim commented on .github/workflows/prod-image-tag.yml
> +      output1: ${{ steps.step-for-image-tag.outputs.image-tag }}
b6c7409 변경에 문제 없어 변경 하였습니다! prod/staging-image-tag.yml 모두 의미에 맞게 반영하였습니다!

2022-12-07 04:36 UTC, myeongjunkim commented on .github/workflows/update-k8s-mainifest.yml
> +          target_branch: test-ci
감사합니다. 혹시 이부분에 대해서도 test 를 위해 모든 작업 이후에 마무리 수정으로 진행해도 될까요?!

2022-12-07 04:39 UTC, myeongjunkim commented on .gitignore
> +staging.yml
d797fb5 앗 이부분은 제가 참고용으로 가져다 놓은 파일들이였습니다. 제거 후 gitignore도 수정하였습니다!

2022-12-07 04:41 UTC, myeongjunkim commented on .github/workflows/draft-release.yml
> +          config-name: config.yml
228463d 그렇군요! draft-release.yml 에 대해서는 테스트가 진행되지 않은 상황이라 확인이 필요할 것 같습니다. 파일 추가 완료하였습니다.

2022-12-07 11:27 UTC, sjquant requested changes

2022-12-07 11:27 UTC, sjquant commented on .github/workflows/build-push.yml
> +          ECR_REGISTRY: 650976052998.dkr.ecr.ap-northeast-2.amazonaws.com
이거 들어가면 안됩니다. (집주소와 같은것..)
`inputs`로 대체해주세요.

2022-12-07 11:27 UTC, sjquant commented on .github/workflows/prod-image-tag.yml
> +      - id: step-for-release-tag
id에 `step-for`라는 prefix를 추가한 이유가 있을까요?

2022-12-07 11:27 UTC, sjquant commented on .github/workflows/update-k8s-mainifest.yml
> +          target_repository: alphaprime-dev/alphasquare-infra
여기도 inputs로 대체해주셔야 할 것 같습니다.

2022-12-08 00:29 UTC, sawaca96 commented on .github/workflows/build-push.yml
> +  called-job:
아하. 개인적으로는 called-job은 사용자 입장에서 뭘 말하는 건지 알기 어렵다고 느껴져서요. 

반복이 나을 것 같은데 어떻게 생각하세요?

2022-12-08 00:29 UTC, sawaca96 commented on .github/workflows/draft-release.yml
> +          config-name: config.yml
이거 단순히 파일 추가하는것으로는 해결 안된다고 했던 것 같은데 아직 작업중인걸까요?

2022-12-08 07:43 UTC, myeongjunkim commented on .github/workflows/update-k8s-mainifest.yml
> +          target_repository: alphaprime-dev/alphasquare-infra
c3538fe9ad19aa7e126beb20a4eb99e51ee55ef8 대체 하였습니다!

2022-12-08 07:46 UTC, myeongjunkim commented on .github/workflows/prod-image-tag.yml
> +      - id: step-for-release-tag
229ad4f 불필요한것 같습니다. 삭제하였습니다!

2022-12-08 07:57 UTC, sjquant approved these changes
고생하셨습니다!
훨씬 사용성 좋을것 같아요 :)

2022-12-08 08:04 UTC, sawaca96 reviewed
👍👍👍 LGTM

2022-12-08 08:16 UTC, myeongjunkim commented on .github/workflows/build-push.yml
> +  called-job:
8c4cfd3 좋은 것 같습니다. 수정완료하였습니다!

2022-12-08 08:37 UTC, sawaca96 approved these changes

2022-12-08 08:44 UTC, merged